info:
  app:
    name: imgtag-service
    description: Manages the imgtags of photos

server:
  port: 8025

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

microservice:
  nbsokContentUrl: http://www.nb.no/nbsok/nb/{sesamid}
  fotoContentUrl: http://www.nb.no/foto/nb/{sesamid}
